import Foundation

// MARK: - AVBeamMessageDelegate

/**
 * Delegate protocol for handling general messages and errors from the AVBeam system.
 *
 * Implement this protocol to receive and handle errors and notifications that are
 * not specific to any particular functionality.
 */
public protocol AVBeamMessageDelegate: AnyObject {
  /**
   * Called when an error occurs during any AVBeam operation.
   *
   * @param error The error that occurred.
   */
  func didReceiveError(error: AVBeamError)

  /**
   * Called when a notification is generated by the AVBeam system.
   *
   * @param notification The notification that was generated.
   */
  func didReceiveNotification(notification: AVBeamNotification)
}
